# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69eeedcd217cf1a8d0252c5c6b895ea6f427fa6f30c52689aaa6ac5b0a9c1dbcd097fed7b8a04fc3653306446080a1f0221d1f4c91c5d4199ca6accba248ff68

test:
  secret_key_base: 51cfdba682e942743640aaed303db88f0afc4c6cfc5619ad3c1c7eb4a4b7226871d0c85eaa666f533771c4f1dd8f41e75dc6eb1ebcac09210c4498ee64c633de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
